//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetWebApp.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetValue
    {
        public string Username { get; set; }
        public Nullable<int> FinalBudget { get; set; }
        public Nullable<int> IncomeLessTax { get; set; }
        public Nullable<int> MonthlyExpenses { get; set; }
        public Nullable<int> HomeLoanExpense { get; set; }
        public Nullable<int> VehicleExpense { get; set; }
        public Nullable<int> RentExpense { get; set; }
    }
}
