//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetWebApp.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetAppEntities : DbContext
    {
        public BudgetAppEntities()
            : base("name=BudgetAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetSaving> BudgetSavings { get; set; }
        public virtual DbSet<BudgetValue> BudgetValues { get; set; }
        public virtual DbSet<UserCredential> UserCredentials { get; set; }
    }
}
